myproject/diary/urls.py
from django.urls import path
from . import views

app_name = 'diary'
urlpatterns = [
    path('', views.index, name='index'),
    path('page/create/', views.page_create, name='page_create'),
    path('pages/', views.page_list, name='page_list'),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('diary/', include('diary.urls'))
]

myproject/diary/models.py
from django.db import models
import uuid

class Page(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False, verbose_name="ID")
    title = models.CharField(max_length=100, verbose_name="タイトル")
    body = models.TextField(max_length=2000, verbose_name="本文")
    page_date = models.DateField(verbose_name="日付")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="作成日時")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="更新日時")
    
    def __str__(self):
        return self.title

myproject/diary/forms.py
from django.forms import ModelForm
from .models import Page

class PageForm(ModelForm):
    class Meta:
        model = Page
        fields = ["title", "body", "page_date"]

myproject/diary/views.py
from django.shortcuts import render, redirect
from django.views import View
from .forms import PageForm
from .models import Page
from datetime import datetime
from zoneinfo import ZoneInfo

class IndexView(View):
    def get(self, request):
        datetime_now = datetime.now(
            ZoneInfo("Asia/Tokyo")
        ).strftime("%Y年%m月%d日 %H:%M:%S")
        return render(
            request, 'diary/index.html', {"datetime_now": datetime_now})

class PageCreateView(View):
    def get(self, request):
        form = PageForm()
        return render(request, "diary/page_form.html", {"form":form})
    
    def post(self, request):
        form = PageForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("diary:index")
        return render(request, "diary/page_form.html", {"form":form})

class PageListView(View):
    def get(self, request):
        page_list = Page.objects.order_by("-page_date")
        return render(request, "diary/page_list.html", {"page_list":page_list})

index = IndexView.as_view()
page_create = PageCreateView.as_view()
page_list = PageListView.as_view()

myproject/templates/base/diary_base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta charset="utf-8">
        <title>Userの日記</title>
    </head>
    <body>
        <h1><a href="{% url 'diary:index' %}">Userの日記</a></h1>
        {% block body %}
        {% endblock %}
    </body>
</html>

myproject/templates/diary/index.html
{% extends "base/diary_base.html" %}
{% block body %}

<p>{{ datetime_now }}</p>
<br>
<a href="{% url 'diary:page_create' %}">日記を書く</a>
<br>
<a href="{% url 'diary:page_list' %}">ページ一覧</a>

{% endblock %}

myproject/templates/diary/page_form.html
{% extends "base/diary_base.html" %}
{% block body %}

<h2>日記を書く</h2>
<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">保存</button>
</form>

{% endblock %}

myproject/templates/diary/page_list.html
{% extends "base/diary_base.html" %}
{% block body %}

<ul>
    {% for page in page_list %}
    <li>{{ page.page_date }}: {{ page.title }}</li>
    {% empty %}
        <div>日記のページが見つかりません</div>
    {% endfor %}
</ul>

{% endblock %}